# Generated by Django 4.0.4 on 2022-06-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_poster',
            field=models.ImageField(height_field='height', null=True, upload_to='images/', width_field='width'),
        ),
    ]
